/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _REMOTEPROC_H_RPCGEN
#define _REMOTEPROC_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


typedef struct {
	u_int data_len;
	int *data_val;
} data;

typedef struct {
	u_int new_array_len;
	float *new_array_val;
} new_array;

struct result1 {
	int max;
	int min;
};
typedef struct result1 result1;

struct argument1 {
	struct {
		u_int data_len;
		int *data_val;
	} data;
	float r;
};
typedef struct argument1 argument1;

#define MATHPROG 0x20000008
#define MATHVERBS 1

#if defined(__STDC__) || defined(__cplusplus)
#define MeshTimh 1
extern  float * meshtimh_1(data *, CLIENT *);
extern  float * meshtimh_1_svc(data *, struct svc_req *);
#define MaxMin 2
extern  result1 * maxmin_1(data *, CLIENT *);
extern  result1 * maxmin_1_svc(data *, struct svc_req *);
#define PowerArray 3
extern  new_array * powerarray_1(argument1 *, CLIENT *);
extern  new_array * powerarray_1_svc(argument1 *, struct svc_req *);
extern int mathprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define MeshTimh 1
extern  float * meshtimh_1();
extern  float * meshtimh_1_svc();
#define MaxMin 2
extern  result1 * maxmin_1();
extern  result1 * maxmin_1_svc();
#define PowerArray 3
extern  new_array * powerarray_1();
extern  new_array * powerarray_1_svc();
extern int mathprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_data (XDR *, data*);
extern  bool_t xdr_new_array (XDR *, new_array*);
extern  bool_t xdr_result1 (XDR *, result1*);
extern  bool_t xdr_argument1 (XDR *, argument1*);

#else /* K&R C */
extern bool_t xdr_data ();
extern bool_t xdr_new_array ();
extern bool_t xdr_result1 ();
extern bool_t xdr_argument1 ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_REMOTEPROC_H_RPCGEN */
