/*
 *	Author: Oulis Evangelos
 *	Class:	Friday 2-4
 *	Subject:	Distributed Systems
 *	Description:	RPC Server code.
 *	File Name:	remoteproc_server.c
 */

/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include <time.h>
#include "remoteproc.h"

float *
meshtimh_1_svc(data *argp, struct svc_req *rqstp)
{
	time_t s = time(NULL);
	struct tm *current_time;
	current_time = localtime(&s);
	
	printf("[%02d:%02d:%02d]\t:\t", current_time->tm_hour, current_time->tm_min, current_time->tm_sec);
	
	printf ("->Mesh Timh Functrion called!\n");
	static float  result;

	int count=0, sum=0, j;
	for (j=0; j<argp->data_len; j++)
	{
		count++;
		sum += argp->data_val[j];
	}
	
	float mesh_timh = (float) sum/count;
	
	result = mesh_timh;

	return &result;
}

result1 *
maxmin_1_svc(data *argp, struct svc_req *rqstp)
{
	time_t s = time(NULL);
	struct tm *current_time;
	current_time = localtime(&s);
	
	printf("[%02d:%02d:%02d]\t:\t", current_time->tm_hour, current_time->tm_min, current_time->tm_sec);
	
	printf ("->Find Max & Miv vector times called!\n");
	static result1  result;

	int max=argp->data_val[0];
	int min=argp->data_val[0];
	
	int j;
	for(j=0; j<argp->data_len; j++)
	{
		if (argp->data_val[j] > max)
			max=argp->data_val[j];
		if (argp->data_val[j] < min)
			min=argp->data_val[j];
	}
				
	result.max=max;
	result.min=min;

	return &result;
}

new_array *
powerarray_1_svc(argument1 *argp, struct svc_req *rqstp)
{
	time_t s = time(NULL);
	struct tm *current_time;
	current_time = localtime(&s);
	
	printf("[%02d:%02d:%02d]\t:\t", current_time->tm_hour, current_time->tm_min, current_time->tm_sec);
	
	printf ("->Ypsosh Dianhsmatos se Dynamh Function Called!\n");
	static new_array  result;

	result.new_array_len = argp->data.data_len;
	result.new_array_val = (float *)malloc(argp->data.data_len *sizeof(float));
	float r = argp->r;
	
	int j;
	for (j=0; j<argp->data.data_len; j++)
	{
		result.new_array_val[j] = argp->data.data_val[j] * r;
	}

	return &result;
}
