/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "remoteproc.h"


void
mathprog_1(char *host)
{
	CLIENT *clnt;
	float  *result_1;
	data  meshtimh_1_arg;
	result1  *result_2;
	data  maxmin_1_arg;
	new_array  *result_3;
	argument1  powerarray_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, MATHPROG, MATHVERBS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = meshtimh_1(&meshtimh_1_arg, clnt);
	if (result_1 == (float *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = maxmin_1(&maxmin_1_arg, clnt);
	if (result_2 == (result1 *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_3 = powerarray_1(&powerarray_1_arg, clnt);
	if (result_3 == (new_array *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	mathprog_1 (host);
exit (0);
}
