/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "remoteproc.h"

bool_t
xdr_data (XDR *xdrs, data *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->data_val, (u_int *) &objp->data_len, ~0,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_new_array (XDR *xdrs, new_array *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->new_array_val, (u_int *) &objp->new_array_len, ~0,
		sizeof (float), (xdrproc_t) xdr_float))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_result1 (XDR *xdrs, result1 *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->max))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->min))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_argument1 (XDR *xdrs, argument1 *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->data.data_val, (u_int *) &objp->data.data_len, ~0,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->r))
		 return FALSE;
	return TRUE;
}
